### ISSUE TITLE
Seed error

### ISSUE THREAD

**Issue by SimoMay** [mercurjs/mercur#2]
Running `yarn seed` in **api folder** finishes migrations successfully but throws an error:

```
....
info:    Migrations completed.
[medusa-config] ⚠️ redis_url not found. A fake redis instance will be used.
[medusa-config] ⚠️ jwt_secret not found. fallback to either cookie_secret or default 'supersecret'.
[medusa-config] ⚠️ cookie_secret not found. fallback to either cookie_secret or default 'supersecret'.
info:    Using fake Redis
✔ Models initialized – 16ms
✔ Plugin models initialized – 8ms
✔ Strategies initialized – 11ms
✔ Database initialized – 44ms
✔ Repositories initialized – 16ms
✔ Services initialized – 32ms
⠋ Initializing modules
✔ Modules initialized – 55ms
✔ Express intialized – 2ms
⠋ Initializing plugins
✔ Plugins intialized – 21ms
✔ Subscribers initialized – 5ms
✔ API initialized – 18ms
⠋ Initializing defaults
warn:    You don't have any notification provider plugins installed. You may want to add one to your project.
✔ Defaults initialized – 48ms
⠋ Initializing search engine indexing
✔ Indexing event emitted – 1ms
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __values (/.../marketplace/api/node_modules/@medusajs/medusa/dist/commands/seed.js:73:72)
    at /.../marketplace/api/node_modules/@medusajs/medusa/dist/commands/seed.js:455:54
    at step (/.../marketplace/api/node_modules/@medusajs/medusa/dist/commands/seed.js:67:23)
    at Object.next (/.../marketplace/api/node_modules/@medusajs/medusa/dist/commands/seed.js:48:53)
    at fulfilled (/.../marketplace/api/node_modules/@medusajs/medusa/dist/commands/seed.js:39:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by SimoMay** [comment]
I posted the error and solution in the correct repo
https://github.com/mercurjs/mercur-api-starter/pull/6#issue-2295094880
This can safely close

**Comment by lokichaulagain** [comment]
> I posted the error and solution in the correct repo [mercurjs/mercur-api-starter#6 (comment)](https://github.com/mercurjs/mercur-api-starter/pull/6#issue-2295094880) This can safely close

Still its not working .
Here is my error.
![image](https://github.com/mercurjs/mercur/assets/81034183/c2676ef4-10ab-465d-aff7-a13d1749ae62)
